server:
  port: 8052
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  profiles:
    active: production
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true